### PR TITLE
Setup build

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Review by MaisiKoleni — CHANGES_REQUESTED** [review]
First, thanks for contributing! Yes, the automated build has been missing so far. I will take a look at it in more detail later.
It seems that many .class files ended up in the PR accidentally, though.

**Comment by mickaelistria** [comment]
Thanks for the review, I updated the PR to remove the bin/ folder.

**Review by MaisiKoleni — APPROVED** [review]
Looks good, installation after `mvn verfiy` works fine.

Just one last question, is there any benefit in using the I-Builds repository opposed to, e.g., the R-Builds repository?

**Comment by mickaelistria** [comment]
> Just one last question, is there any benefit in using the I-Builds repository opposed to, e.g., the R-Builds repository?

It depends on your target audience. As most of JDT developers use the I-Build of the SDK to developer and target development of I-Build, I found it more interesting to build against I-Build to ensure more compatibility; but using releases would be fine too.

**Pull request merged**
